-- AlterTable
ALTER TABLE `Product` ADD COLUMN `createdAt` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    MODIFY `name` VARCHAR(255) NOT NULL;

-- AlterTable
ALTER TABLE `Shop` ADD COLUMN `createdAt` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    MODIFY `name` VARCHAR(255) NOT NULL,
    MODIFY `address` VARCHAR(255) NULL;

-- AlterTable
ALTER TABLE `User` ADD COLUMN `createdAt` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    ADD COLUMN `role` VARCHAR(255) NULL,
    MODIFY `email` VARCHAR(255) NOT NULL,
    MODIFY `username` VARCHAR(255) NULL,
    MODIFY `password` VARCHAR(255) NULL;
